### ISSUE TITLE
SAGU - Residência Multiprofissional - Implementação da área administrativa (supervisor por município/hospital, residente)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu#28]
Novo perfil: Supervisor de residência

Eu como supervisor
Quero realizar o acompanhamento dos residentes de um determinado município e hospital
Para que possa ser feito o levantamento e gerenciamento de notas, frequências e relatórios dos residentes.

Contexto
Atualmente o acompanhamento de residentes é feito de forma centralizada, pelo setor que gerencia a residência multiprofissional. A implementação dessa funcionalidade, descentraliza o gerenciamento continuo de residentes.

Responsabilidade supervisor: 
- Alimentação de faltas residentes
- Avaliação discente (Nota de avaliação de desempenho) + Avaliação da atividade de produto (nota)
- Carga horária complementar
- Relatórios

Escopo

- SAGU
- [x] Implementar gerenciamento de supervisores
- [x] Implementar vínculos, oferta de atividade do módulo, supervisor e instituição.

API
- [ ] Implementar configuração de ambiente (API)
- [ ] Implementar endpoint autenticação do supervisor
- [ ] Implementar endpoint listagem de ofertas de módulos em que o usuário (supervisor) logado possa acessar os vínculos
- [ ] Implementar endpoint para realizar lançamento de faltas
- [ ] Implementar endpoint para realizar lançamento de notas
- [ ] Implementar endpoint para realizar lançamento de carga horária complementar
- [ ] Implementar endpoint para relatórios

**Comment by vicmagpac** [comment]
Proposta fluxo front sagu para o supervisor

```
@startmindmap
* Login
** Turmas
*** Ofertas de atividades dos módulos
**** Residentes matrículados na oferta
***** Lançamento de falta
***** Lançamento de notas
***** Lançamento de carga horária complementar
@endmindmap
```
Proposta 1
![fluxo-front-sagu](https://user-images.githubusercontent.com/3487411/117992105-097ffd00-b315-11eb-9ecc-1a2468b2ca9c.png)

Proposta 2
![Screenshot from 2021-05-14 09-45-35](https://user-images.githubusercontent.com/3487411/118272579-30ffd280-b499-11eb-9358-b87ae7fd5d86.png)



Necessário validar.
